<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>CJDSL.Api</AssemblyName>
    <RootNamespace>CJDSL.Api</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CJDSL.Application\CJDSL.Application.csproj" />
    <ProjectReference Include="..\CJDSL.Infrastructure\CJDSL.Infrastructure.csproj" />
    <ProjectReference Include="..\CJDSL.Generation\CJDSL.Generation.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Swashbuckle.AspNetCore" />
  </ItemGroup>

</Project>
