<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <AssemblyName>CJDSL.Web</AssemblyName>
    <RootNamespace>CJDSL.Web</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CJDSL.Api\CJDSL.Api.csproj" />
    <ProjectReference Include="..\CJDSL.Blazor\CJDSL.Blazor.csproj" />
    <ProjectReference Include="..\..\..\CJCore\src\Framework\CJCore.Framework\CJCore.Framework.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MudBlazor" />
  </ItemGroup>

</Project>
