<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <AssemblyName>CJDSL.Blazor</AssemblyName>
    <RootNamespace>CJDSL.Blazor</RootNamespace>
    <AddRazorSupportForMvc>true</AddRazorSupportForMvc>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CJDSL.Domain\CJDSL.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components" />
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" />
    <PackageReference Include="MudBlazor" />
    <PackageReference Include="Jint" />
  </ItemGroup>

</Project>
