<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>CJDSL.Application</AssemblyName>
    <RootNamespace>CJDSL.Application</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CJDSL.Domain\CJDSL.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MediatR" />
    <PackageReference Include="AutoMapper" />
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
  </ItemGroup>

</Project>
